### ISSUE TITLE
litepresence doesn't start on NixOS

### ISSUE THREAD

**Issue by Alxhr0** [TorchedSammy/litepresence#1]
i followed the instructions installed it fully closed lite-xl and it doesn't start rpc doesn't show unless i will start litepresence myself but it only shows that i'm idling it doesn't show what file i'm editing etc

**Comment by sammy-ette** [comment]
this is probably somehow an issue with the path it uses to run so just specify `config.plugins.litepresence.binpath` to something

this sounds like the average nixos issue
