### ISSUE TITLE
Discord flatpak support?

### ISSUE THREAD

**Issue by Alxhr0** [TorchedSammy/litepresence#2]
Discord Flatpak now supports Discord RPC which can be enabled with 

``mkdir -p ~/.config/user-tmpfiles.d
echo 'L %t/discord-ipc-0 - - - - app/com.discordapp.Discord/discord-ipc-0' > ~/.config/user-tmpfiles.d/discord-rpc.conf
systemctl --user enable --now systemd-tmpfiles-setup.service``

But litepresence doesn't work with it because it searches for /run/user/1000/discord-ipc-0
the flatpak version has discord-ipc-0 in ``/run/user/1000/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-0``

**Comment by sammy-ette** [comment]
open an issue on https://github.com/hugolgst/rich-go
