### ISSUE TITLE
Litepresence: !? Binary quit unexpectedly (MacOS)

### ISSUE THREAD

**Issue by ghost** [TorchedSammy/litepresence#3]
When starting lite-xl, i am greeted with "Litepresence: !? Binary quit unexpectedly". When running in the terminal, the following output is presented.
`❯ ./litepresence`
`panic: dial unix /var/folders/4x/ht_yl9gs25nfwyq_b2hqw5x40000gn/T//discord-ipc-0: connect: no such file or directory`

`goroutine 1 [running]:`
`main.main()`
`/Users/bedtime/Development/litepresence/main.go:27 +0xfe`

**Comment by sammy-ette** [comment]
open an issue at https://github.com/hugolgst/rich-go
(it should work on macos though so that's odd)
