### ISSUE TITLE
LiteXL v2.1 support?

### ISSUE THREAD

**Issue by Not-a-web-Developer** [TorchedSammy/litepresence#7]
for now, only the first line needs to be changed from 
```lua
-- mod-version:2 -- lite-xl 2.0
```
to
```lua
-- mod-version:3 -- lite-xl 2.1
```
for getting the plugin working on LiteXL's `master-2.1` branch. however, it would be nice for y'all to look through the codebase to make sure there aren't potential incompatibilities that can cause problems in the future.

**Comment by sammy-ette** [comment]
fixed by #9
